artifacts: 
  discard-paths: true
  files: 
    - target/*.*
    - target/site/cobertura/coverage.xml
phases: 
  build: 
    commands: 
      - "echo Entered the build phase..."
      - "echo Build started on `date`"
      #- "mvn install"
      - 'mvn clean package cobertura:cobertura -Pmetrics'
version: 0.2
